# Generated by Django 2.1.1 on 2018-12-27 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20181227_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 47, 29, 837003)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_img/default.png', upload_to='media/post_img/'),
        ),
    ]
